// Basic state of our chest items

export const state = {
  chestState: {
    block00: { item: "diamond" },
    block10: { item: null },
    block20: { item: "bone" },
    block30: { item: null },
    block40: { item: null },
    block50: { item: null },
    block60: { item: null },
    block70: { item: null },
    block80: { item: null },
    block01: { item: null },
    block11: { item: null },
    block21: { item: null },
    block31: { item: null },
    block41: { item: null },
    block51: { item: null },
    block61: { item: null },
    block71: { item: null },
    block81: { item: null },
    block02: { item: null },
    block12: { item: null },
    block22: { item: null },
    block32: { item: null },
    block42: { item: null },
    block52: { item: "apple" },
    block62: { item: null },
    block72: { item: null },
    block82: { item: null },
  },
  inventoryState: {
    block00: { item: null },
    block10: { item: null },
    block20: { item: null },
    block30: { item: null },
    block40: { item: null },
    block50: { item: null },
    block60: { item: null },
    block70: { item: null },
    block80: { item: null },
    block01: { item: null },
    block11: { item: null },
    block21: { item: null },
    block31: { item: null },
    block41: { item: null },
    block51: { item: null },
    block61: { item: null },
    block71: { item: null },
    block81: { item: "diamond" },
    block02: { item: null },
    block12: { item: null },
    block22: { item: null },
    block32: { item: null },
    block42: { item: "beef" },
    block52: { item: null },
    block62: { item: null },
    block72: { item: null },
    block82: { item: null },
  },
  hotBarState: {
    block00: { item: null },
    block10: { item: null },
    block20: { item: null },
    block30: { item: null },
    block40: { item: null },
    block50: { item: null },
    block60: { item: null },
    block70: { item: null },
    block80: { item: null },
  },
};
